name: lab2_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h26f9b46_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py310h7c4b9e2_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h387f397_9
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - adal==1.2.7
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alembic==1.15.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argcomplete==3.6.2
      - asgiref==3.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - azure-core==1.36.0
      - azure-identity==1.25.1
      - azure-mgmt-core==1.6.0
      - azureml-dataprep==5.1.6
      - azureml-dataprep-native==41.0.0
      - azureml-dataprep-rslex==2.22.5
      - backports-tempfile==1.0
      - backports-weakref==1.0.post1
      - bcrypt==4.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.0
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - contextlib2==21.6.0
      - contourpy==1.3.2
      - cryptography==45.0.2
      - cycler==0.12.1
      - databricks-sdk==0.53.0
      - deprecated==1.2.18
      - distro==1.9.0
      - docker==7.1.0
      - fastapi==0.115.12
      - filelock==3.18.0
      - fixedint==0.1.6
      - flask==3.1.1
      - fonttools==4.58.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.182.0
      - google-auth==2.40.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.2
      - grpcio==1.75.0
      - grpcio-status==1.71.2
      - gunicorn==23.0.0
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jeepney==0.9.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.0
      - jsonpickle==4.0.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - knack==0.12.0
      - lazy-loader==0.4
      - mako==1.3.10
      - markdown==3.8
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - milvus-lite==2.5.1
      - mldesigner==0.1.0b19
      - mlflow==2.22.0
      - mlflow-skinny==2.22.0
      - mltable==1.6.1
      - mpmath==1.3.0
      - msal==1.32.3
      - msal-extensions==1.3.1
      - msrest==0.7.1
      - msrestazure==0.6.4.post1
      - multidict==6.6.4
      - ndg-httpsclient==0.5.1
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.2.2
      - openai==1.99.1
      - opentelemetry-api==1.31.1
      - opentelemetry-instrumentation==0.52b1
      - opentelemetry-instrumentation-asgi==0.52b1
      - opentelemetry-instrumentation-dbapi==0.52b1
      - opentelemetry-instrumentation-django==0.52b1
      - opentelemetry-instrumentation-fastapi==0.52b1
      - opentelemetry-instrumentation-flask==0.52b1
      - opentelemetry-instrumentation-psycopg2==0.52b1
      - opentelemetry-instrumentation-requests==0.52b1
      - opentelemetry-instrumentation-urllib==0.52b1
      - opentelemetry-instrumentation-urllib3==0.52b1
      - opentelemetry-instrumentation-wsgi==0.52b1
      - opentelemetry-resource-detector-azure==0.1.5
      - opentelemetry-sdk==1.31.1
      - opentelemetry-semantic-conventions==0.52b1
      - opentelemetry-util-http==0.52b1
      - packaging==24.2
      - pandas==2.2.3
      - paramiko==3.5.1
      - pathspec==0.12.1
      - pillow==11.2.1
      - pkginfo==1.12.1.2
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==6.1.1
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydash==8.0.5
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pymilvus==2.6.1
      - pynacl==1.5.0
      - pyopenssl==25.1.0
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rpds-py==0.25.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - secretstorage==3.3.3
      - sentence-transformers==5.1.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - sqlparse==0.5.3
      - starlette==0.46.2
      - strictyaml==1.7.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.21.4
      - torch==2.9.0
      - torch-geometric==2.7.0
      - tqdm==4.67.1
      - transformers==4.55.0
      - triton==3.5.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - ujson==5.10.0
      - uritemplate==4.2.0
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xxhash==3.6.0
      - yarl==1.20.1
      - zipp==3.21.0
prefix: /home/noamsasson/miniconda3/envs/lab2_env
