name: lab2_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.8.3=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.13.7=py313hd8ed1ab_100
  - debugpy=1.8.17=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=9.5.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.3=h725018a_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py313h5ea7bf4_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.13.7=hdf00ec1_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.7=h4df99d1_100
  - python_abi=3.13=8_cp313
  - pywin32=311=py313h40c08fc_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.2=py313h5ea7bf4_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.2
      - google-api-python-client==2.184.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - httplib2==0.31.0
      - huggingface-hub==0.35.3
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.6.4
      - networkx==3.3
      - numpy==2.3.3
      - pandas==2.3.2
      - pillow==11.0.0
      - propcache==0.4.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pymilvus==2.6.2
      - pyparsing==3.2.5
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentence-transformers==5.1.1
      - setuptools==80.9.0
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.7.1+cu118
      - torch-geometric==2.6.1
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - transformers==4.57.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - yarl==1.20.1
prefix: C:\Users\Lenovo\miniconda3\envs\lab2_env
